myName = input ("What's you name: ")
myAge = input ("How old are you? :")
print ( "Gee, that's REALLY OLD")
replit = input (" Do you like Replit? ")
print (" OF COURSE YOU DO!" )
print ()
print ( "So, you are ")
print ( "Elvira")
print ( "and are the ripe old age of")
print ("31")
print ( "and clearly think that replit is")
print (replit)